context("Stopwatch")

test_that("Stopwatch Time Works",  {
  st = Stopwatch$new(time_budget = 3L)
  st$per_fit_time = 0L
  expect_true(st$get_time_left() >= 1)
  expect_false(st$stop())
  Sys.sleep(.2)
  expect_false(st$stop())
  Sys.sleep(.2)
  expect_false(st$stop())
  Sys.sleep(1)
  expect_true(st$get_time_left() >= 1)
  Sys.sleep(1.6)
  expect_true(st$stop())
  expect_true(st$get_time_left() < 0)
  Sys.sleep(1)
  expect_true(st$stop())
  expect_true(st$get_time_left() < 0)
  st$start()
  expect_true(st$get_time_left() >= 1)
  expect_false(st$stop())
})

test_that("Stopwatch Iterations works",  {
  st = Stopwatch$new(iterations = 10L)
  expect_false(st$stop())
  expect_true(st$current_iter == 0L)
  st$increment_iter(1)
  expect_false(st$stop())
  expect_true(st$current_iter == 1L)
  st$increment_iter(2)
  expect_false(st$stop())
  expect_true(st$current_iter == 3L)
  st$increment_iter(1)
  expect_false(st$stop())
  expect_true(st$current_iter == 4L)
  st$increment_iter(5)
  expect_false(st$stop())
  expect_true(st$current_iter == 9L)
  st$increment_iter(1)
  expect_true(st$current_iter == 10L)
  expect_true(st$stop())
  st$increment_iter(1)
  expect_true(st$current_iter == 11L)
  expect_true(st$stop())
})
